### ISSUE TITLE
Finish up UI of main pages

### ISSUE THREAD

**Issue by Tina-otoge** [GamesWithoutBait/proto#31]
- [ ] Rating is not perfectly aligned in games list
- [ ] Rating is too close to text in game page
- [ ] Genres and platforms should be displayed in badges
- [ ] Reviews should have their own box
- [ ] We should be able to see review time
- [ ] We should be able to see review tags
- [ ] Filtering / Sorting from game listing
- [ ] Pagination for reviews (tracked in https://github.com/GamesWithoutBait/proto/issues/20)
- [ ] Visuals for logos / icons (tracked in https://github.com/GamesWithoutBait/proto/issues/3)
- [ ] Making the review form interactive and with attractive buttons (tracked in https://github.com/GamesWithoutBait/proto/issues/28)
- [ ] Same for new game form (tracked in https://github.com/GamesWithoutBait/proto/issues/26)
